services:

  propostaservice:
    container_name: proposta-service
    build:
      context: PropostaService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DEFAULT_PROPOSTA_CONNECTION}
      - AWS_REGION=${AWS_REGION}
      - SNS_PROPOSTA_EVENTS=${SNS_PROPOSTA_EVENTS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


  contratacaoservice:
    container_name: contratacao-service
    build:
      context: ContratacaoService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONTRATACAO_CONNECTION}
      - Services__PropostaServiceUrl=http://propostaservice:8080
      - SQS_PROPOSTA_EVENTS=${SQS_PROPOSTA_EVENTS}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}